services:
  postgres:
    image: postgres:15-alpine
    container_name: yt-mp3-postgres
    environment:
      - POSTGRES_DB=${DB_NAME:-youtube_converter}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-youtube_converter}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M


  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    user: "0:0"  # Run as root to fix permissions
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-youtube_converter}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_TYPE=${DB_TYPE:-postgres}
      - PORT=${PORT:-3001}
      - MAX_WORKERS=${MAX_WORKERS:-8}
      - MAX_CONCURRENT_JOBS=${MAX_CONCURRENT_JOBS:-20}
      - MAX_CACHE_SIZE=${MAX_CACHE_SIZE:-1000}
      - CACHE_TTL=${CACHE_TTL:-3600000}
      - DOWNLOADS_DIR=${DOWNLOADS_DIR:-/app/downloads}
      - CACHE_DIR=${CACHE_DIR:-/app/cache}
      - TEMP_DIR=${TEMP_DIR:-/app/temp}
      - MAX_FILE_AGE_HOURS=${MAX_FILE_AGE_HOURS:-24}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-20}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENABLE_METRICS=${ENABLE_METRICS:-true}
      - DISABLE_SOURCE_MAPS=${DISABLE_SOURCE_MAPS:-true}
      - HIDE_SERVER_INFO=${HIDE_SERVER_INFO:-true}
      - SECURE_HEADERS=${SECURE_HEADERS:-true}
      - RAPIDAPI_KEY=${RAPIDAPI_KEY:-546e353d67msha411dc0cd0b0b7dp153e93jsn651c16a2c85b}
    volumes:
      - ./downloads:/app/downloads:rw
      - ./cache:/app/cache:rw
      - ./temp:/app/temp:rw
      - ./logs:/app/logs:rw
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.5'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - VITE_API_URL=${VITE_API_URL:-https://saveytb.com/api}
      - VITE_APP_NAME=${VITE_APP_NAME:-YouTube to MP3 Converter}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
      - DISABLE_SOURCE_MAPS=${DISABLE_SOURCE_MAPS:-true}
      - SECURE_HEADERS=${SECURE_HEADERS:-true}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: yt-mp3-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-main.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M


volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

 